### ISSUE TITLE
RSVP button links to old meetup event

### ISSUE THREAD

**Issue by kacollins** [techlahoma/okcsharp-website#34]
https://github.com/techlahoma/okcsharp-website/blob/ea1d428976070cafa240bac9efd4d61d0a209214/themes/landscape/layout/_widget/rsvp.ejs#L5

**Comment by the-simian** [comment]
references #35

**Comment by davidroberts63** [comment]
This is mostly fixed as of #37. There was a problem with each link needing it's own RSVP token that you'd have to get from MeetUp. For now it is a simple link directly to the event in question.
